###### LESSON ONE #######################################################

image lof1 = "images/lesson_one/Lesson 1.1.png"
image lof2 = "images/lesson_one/Lesson 1.2.png"
image lof3 = "images/lesson_one/Lesson 1.3.png"
image lof4 = "images/lesson_one/Lesson 1.4.png"
image lof5 = "images/lesson_one/Lesson 1.5.png"
image lof6 = "images/lesson_one/Lesson 1.6.png"
image lof7 = "images/lesson_one/Lesson 1.7.png"
image lof8 = "images/lesson_one/Lesson 1.8.png"
image lof9 = "images/lesson_one/Lesson 1.9.png"
image lof10 = "images/lesson_one/Lesson 1.10.png"
image lof12 = "images/lesson_one/Lesson 1.12.png"

###### LESSON TWO #######################################################

image ltf1 = "images/lesson_two/Lesson 2.1.png"
image ltf2 = "images/lesson_two/Lesson 2.2.png"
image ltf4 = "images/lesson_two/Lesson 2.4.png"
image ltf5 = "images/lesson_two/Lesson 2.5.png"
image ltf6 = "images/ftg_bg.png"
image ltf7 = "images/lesson_two/Lesson 2.7.png"
image ltf8 = "images/lesson_two/Lesson 2.8.png"
image ltf9 = "images/lesson_two/Lesson 2.9.png"
image ltf10 = "images/lesson_two/Lesson 2.10.png"
image ltf11 = "images/lesson_two/Lesson 2.11.png"
image ltf12 = "images/lesson_two/Lesson 2.12.png"
image ltf13 = "images/lesson_two/Lesson 2.13.png"
image ltf14 = "images/lesson_two/Lesson 2.14.png"
image ltf15 = "images/lesson_two/Lesson 2.15.png"
image ltf16 = "images/lesson_two/Lesson 2.16.png"
image ltf17 = "images/lesson_two/Lesson 2.17.png"
image ltf18 = "images/ftg_bg.png"

###### LESSON THREE #######################################################

image l3f1 = "images/lesson_three/Lesson 3.1.png"
image l3f2 = "images/lesson_three/Lesson 3.2.png"
image l3f3 = "images/lesson_three/lesson 3.3.png"
image l3f4 = "images/lesson_three/Lesson 3.4.png"
image l3f5 = "images/lesson_three/lesson 3.5.png"
image l3f6 = "images/lesson_three/lesson 3.6.png"
image l3f8 = "images/lesson_three/Lesson 3.8.png"
image l3f9 = "images/lesson_three/lesson 3.9.png"

image l3f12 = "images/lesson_three/Lesson 3.12.png"
image l3f13 = "images/lesson_three/Lesson 3.13.png"
image l3f14 = "images/lesson_three/Lesson 3.14.png"
image l3f15 = "images/lesson_three/Lesson 3.15.png"
image l3f16 = "images/lesson_three/Lesson 3.16.png"
image l3f17 = "images/lesson_three/Lesson 3.17.png"
image l3f19 = "images/lesson_three/Lesson 3.19.png"



image l3f20 = "images/lesson_three/Lesson 3.20.png"
image l3f21 = "images/lesson_three/Lesson 3.21.png"
image l3f22 = "images/lesson_three/lesson 3.22.png"
image l3f23 = "images/lesson_three/lesson 3.23.png"
image l3f24 = "images/lesson_three/Lesson 3.24.png"

###### LESSON FOUR #######################################################

image l4f2 = "images/lesson_four/Lesson 4.2.png"
image l4f3 = "images/lesson_four/Lesson 4.3.png"
image l4f4 = "images/lesson_four/Lesson 4.4.png"
image l4f5 = "images/lesson_four/Lesson 4.5.png"
image l4f6 = "images/lesson_four/Lesson 4.6.png"
image l4f7 = "images/lesson_four/Lesson 4.7.png"

image l4f9 = "images/lesson_four/Lesson 4.9.png"
image l4f10 = "images/lesson_four/Lesson 4.10.png"
image l4f11 = "images/lesson_four/Lesson 4.11.png"
image l4f12 = "images/lesson_four/Lesson 4.12.png"
image l4f13 = "images/lesson_four/Lesson 4.13.png"
image l4f14 = "images/lesson_four/Lesson 4.14.png"

image l4f16 = "images/lesson_four/Lesson 4.16.png"
image l4f17 = "images/lesson_four/Lesson 4.17.png"
image l4f18 = "images/lesson_four/Lesson 4.18.png"
image l4f19 = "images/lesson_four/Lesson 4.19.png"
image l4f20 = "images/lesson_four/Lesson 4.20.png"
image l4f21 = "images/lesson_four/Lesson 4.21.png"

image l4f24 = "images/lesson_four/Lesson 4.24.png"
image l4f25 = "images/lesson_four/Lesson 4.25.png"
image l4f26 = "images/lesson_four/Lesson 4.26.png"
image l4f27 = "images/lesson_four/Lesson 4.27.png"
image l4f28 = "images/lesson_four/Lesson 4.28.png"
image l4f29 = "images/lesson_four/Lesson 4.29.png"
image l4f30 = "images/lesson_four/Lesson 4.30.png"
image l4f31 = "images/lesson_four/Lesson 4.31.png"
image l4f32 = "images/lesson_four/Lesson 4.32.png"
image l4f33 = "images/lesson_four/Lesson 4.33.png"
image l4f34 = "images/lesson_four/Lesson 4.34.png"
image l4f38 = "images/lesson_four/Lesson 4.38.png"

###### LESSON FIVE #######################################################

image l5f1 = "images/lesson_five/lesson 5.1.png"
image l5f2 = "images/lesson_five/lesson 5.2.png"
image l5f3 = "images/lesson_five/lesson 5.3.png"
image l5f4 = "images/lesson_five/lesson 5.4.png"
image l5f5 = "images/lesson_five/lesson 5.5.png"
image l5f6 = "images/lesson_five/lesson 5.6.png"
image l5f7 = "images/lesson_five/lesson 5.7.png"
image l5f8 = "images/lesson_five/lesson 5.8.png"
image l5f9 = "images/lesson_five/lesson 5.9.png"
image l5f10 = "images/lesson_five/lesson 5.10.png"
image l5f11 = "images/lesson_five/lesson 5.11.png"
image l5f12 = "images/lesson_five/lesson 5.12.png"
image l5f13 = "images/lesson_five/lesson 5.13.png"
image l5f14 = "images/lesson_five/lesson 5.14.png"
image l5f15 = "images/lesson_five/lesson 5.15.png"
image l5f16 = "images/lesson_five/lesson 5.16.png"
image l5f17 = "images/lesson_five/lesson 5.17.png"
image l5f18 = "images/lesson_five/lesson 5.18.png"
image l5f19 = "images/lesson_five/lesson 5.19.png"

image l5f21 = "images/lesson_five/lesson 5.21.png"
image l5f24 = "images/lesson_five/lesson 5.24.png"
image l5f25 = "images/lesson_five/lesson 5.25.png"
image l5f27 = "images/lesson_five/lesson 5.27.png"
image l5f29 = "images/lesson_five/lesson 5.29.png"
image l5f30 = "images/lesson_five/lesson 5.30.png"
image l5f31 = "images/lesson_five/lesson 5.31.png"
image l5f32 = "images/lesson_five/lesson 5.32.png"
image l5f33 = "images/lesson_five/lesson 5.33.png"
image l5f34 = "images/lesson_five/lesson 5.34.png"
image l5f35 = "images/lesson_five/lesson 5.35.png"
image l5f36 = "images/lesson_five/lesson 5.36.png"
image l5f38 = "images/lesson_five/lesson 5.38.png"
image l5f40 = "images/lesson_five/lesson 5.40.png"
image l5f41 = "images/lesson_five/lesson 5.41.png"

image l5f43 = "images/lesson_five/lesson 5.43.png"
image l5f44 = "images/lesson_five/lesson 5.44.png"
image l5f45 = "images/lesson_five/lesson 5.45.png"
image l5f46 = "images/lesson_five/lesson 5.46.png"
image l5f51 = "images/lesson_five/lesson 5.51.png"
image l5f52 = "images/lesson_five/lesson 5.52.png"
image l5f53 = "images/lesson_five/lesson 5.53.png"
image l5f56 = "images/lesson_five/lesson 5.56.png"
image l5f58 = "images/lesson_five/lesson 5.58.png"

###### LESSON SIX #######################################################

image l6f0 = "images/lesson_six/lesson 6.0.png"
image l6f1 = "images/lesson_six/lesson 6.1.png"
image l6f2 = "images/lesson_six/lesson 6.2.png"
image l6f3 = "images/lesson_six/lesson 6.3.png"
image l6f5 = "images/lesson_six/lesson 6.5.png"
image l6f8 = "images/lesson_six/lesson 6.8.png"
image l6f9 = "images/lesson_six/lesson 6.9.png"
image l6f12 = "images/lesson_six/lesson 6.12.png"
image l6f13 = "images/lesson_six/lesson 6.13.png"
image l6f14 = "images/lesson_six/lesson 6.14.png"
image l6f15 = "images/lesson_six/lesson 6.15.png"
image l6f16 = "images/lesson_six/lesson 6.16.png"
image l6f18 = "images/lesson_six/lesson 6.18.png"
image l6f19 = "images/lesson_six/lesson 6.19.png"
image l6f20 = "images/lesson_six/lesson 6.20.png"
image l6f21 = "images/lesson_six/lesson 6.21.png"
image l6f22 = "images/lesson_six/lesson 6.22.png"
image l6f23 = "images/lesson_six/lesson 6.23.png"
image l6f26 = "images/lesson_six/lesson 6.26.png"
image l6f27 = "images/lesson_six/lesson 6.27.png"
image l6f28 = "images/lesson_six/lesson 6.28.png"
image l6f30 = "images/lesson_six/lesson 6.30.png"
image l6f31 = "images/lesson_six/lesson 6.31.png"
image l6f32 = "images/lesson_six/lesson 6.32.png"
image l6f34 = "images/lesson_six/lesson 6.34.png"
image l6f35 = "images/lesson_six/lesson 6.35.png"
image l6f42 = "images/lesson_six/lesson 6.42.png"

###### LESSON SEVEN #######################################################

image l7f1 = "images/lesson_seven/lesson 7.1.png"
image l7f2 = "images/lesson_seven/lesson 7.2.png"
image l7f3 = "images/lesson_seven/lesson 7.3.png"
image l7f4 = "images/lesson_seven/lesson 7.4.png"
image l7f5 = "images/lesson_seven/lesson 7.5.png"
image l7f10 = "images/lesson_seven/lesson 7.10.png"
image l7f12 = "images/lesson_seven/lesson 7.12.png"
image l7f14 = "images/lesson_seven/lesson 7.14.png"
image l7f15 = "images/lesson_seven/lesson 7.15.png"
image l7f18 = "images/lesson_seven/lesson 7.18.png"
image l7f19 = "images/lesson_seven/lesson 7.19.png"
image l7f22 = "images/lesson_seven/lesson 7.22.png"
image l7f27 = "images/lesson_seven/lesson 7.27.png"

###### LESSON EIGHT #######################################################

image l8f1 = "images/lesson_eight/lesson 8.1.png"
image l8f2 = "images/lesson_eight/lesson 8.2.png"
image l8f3 = "images/lesson_eight/lesson 8.3.png"
image l8f5 = "images/lesson_eight/lesson 8.5.png"
image l8f8 = "images/lesson_eight/lesson 8.8.png"
image l8f10 = "images/lesson_eight/lesson 8.10.png"
image l8f11 = "images/lesson_eight/lesson 8.11.png"
image l8f12 = "images/lesson_eight/lesson 8.12.png"
image l8f13 = "images/lesson_eight/lesson 8.13.png"
image l8f14 = "images/lesson_eight/lesson 8.14.png"
image l8f15 = "images/lesson_eight/lesson 8.15.png"
image l8f16 = "images/lesson_eight/lesson 8.16.png"
image l8f17 = "images/lesson_eight/lesson 8.17.png"
image l8f19 = "images/lesson_eight/lesson 8.19.png"
image l8f21 = "images/lesson_eight/lesson 8.21.png"
image l8f22 = "images/lesson_eight/lesson 8.22.png"
image l8f23 = "images/lesson_eight/lesson 8.23.png"

###### LESSON NINE #######################################################

image l9f1 = "images/lesson_nine/lesson 9.1.png"
image l9f4 = "images/lesson_nine/lesson 9.4.png"
image l9f5 = "images/lesson_nine/lesson 9.5.png"
image l9f7 = "images/lesson_nine/lesson 9.7.png"
image l9f9 = "images/lesson_nine/lesson 9.9.png"
image l9f11 = "images/lesson_nine/lesson 9.11.png"
image l9f12 = "images/lesson_nine/lesson 9.12.png"

###### LESSON TEN #######################################################

image l10f1 = "images/lesson_ten/lesson 10.1.png"
image l10f3 = "images/lesson_ten/lesson 10.3.png"
image l10f4 = "images/lesson_ten/lesson 10.4.png"
image l10f5 = "images/lesson_ten/lesson 10.5.png"
image l10f6 = "images/lesson_ten/lesson 10.6.png"
image l10f8 = "images/lesson_ten/lesson 10.8.png"
image l10f10 = "images/lesson_ten/lesson 10.10.png"
image l10f11 = "images/lesson_ten/lesson 10.11.png"
image l10f12 = "images/lesson_ten/lesson 10.12.png"
image l10f13 = "images/lesson_ten/lesson 10.13.png"
image l10f17 = "images/lesson_ten/lesson 10.17.png"
image l10f18 = "images/lesson_ten/lesson 10.18.png"
image l10f19 = "images/lesson_eight/lesson 8.22.png"